name: "Lumi Home AI"
description: "Premium smart home assistant powered by AI"
version: "1.1.0"
slug: "lumi_demo_ai_v1"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
panel_icon: mdi:robot-outline
panel_title: "Lumi Home Ai"
panel_admin: false
ingress: true
ingress_port: 2454
ports:
  2454/tcp: 2454
homeassistant_api: true
map:
  - config:rw
options:
  ha_wss_url: "ws://supervisor/core/api/websocket"
  long_live_token: ""
  license_key: ""
  ftp_ip: ""
  ftp_port: 21
  ftp_user: ""
  ftp_password: ""
schema:
  ha_wss_url: "str?"
  long_live_token: "password?"
  license_key: "password?"
  ftp_ip: "str?"
  ftp_port: "port?"
  ftp_user: "str?"
  ftp_password: "password?"
